package com.shra1.javamster.dto;

public enum LoginDomainSpecificStatus {
	ACCOUNT_INACTIVE,
	ACCOUNT_LOCKED,
	USERNAME_NOT_FOUND,
	PENDING_VERIFICATION,
	BAD_CREDENTIALS,
	ACCOUNT_DELETED,
	SESSION_EXPIRED,
	TOO_FAST_ATTEMPTS;
}
